### ISSUE TITLE
指定ICON

### ISSUE THREAD

**Issue by cellcb** [twp0217/ngx-timeline#3]
你好 
     event icon 怎样设置 
     自定义的css如下，无法显示图标：
    .icon:before {
        content: url(http://localhost:4200/assets/icons/cloud.svg);
          /*display: inline-block;*/
    }
    thanks

**Comment by twp0217** [comment]
目前不支持自己传底图，现在的icon是引入Font Awesome Icons

**Comment by twp0217** [comment]
周末我重新修改下，让其支持自定义底图功能

**Comment by cellcb** [comment]
多谢
